name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Generate settings.xml for Maven Builds
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: >
          [
            {
              "id": "celements-releases",
              "url": "http://maven.celements.ch/releases",
              "releases": { "enabled": "true" },
              "snapshots": { "enabled": "false" }
            },
            {
              "id": "celements-snapshots",
              "url": "http://maven.celements.ch/snapshots",
              "releases": { "enabled": "false" },
              "snapshots": { "enabled": "true" }
            },
            {
              "id": "celements-externals",
              "url": "http://maven.celements.ch/externals",
              "releases": { "enabled": "true" },
              "snapshots": { "enabled": "true" }
            }
          ]
        mirrors: >
          [
            {
              "id": "xwiki-releases-http-unblocker",
              "mirrorOf": "xwiki-releases",
              "url": "http://maven.xwiki.org/releases"
            },
            {
              "id": "xwiki-snapshots-http-unblocker",
              "mirrorOf": "xwiki-snapshots",
              "url": "http://maven.xwiki.org/snapshots"
            },
            {
              "id": "xwiki-externals-http-unblocker",
              "mirrorOf": "xwiki-externals",
              "url": "http://maven.xwiki.org/externals"
            },
            {
              "id": "celements-releases-http-unblocker",
              "mirrorOf": "celements-releases",
              "url": "http://maven.celements.ch/releases"
            },
            {
              "id": "celements-snapshots-http-unblocker",
              "mirrorOf": "celements-snapshots",
              "url": "http://maven.celements.ch/snapshots"
            },
            {
              "id": "celements-externals-http-unblocker",
              "mirrorOf": "celements-externals",
              "url": "http://maven.celements.ch/externals"
            }
          ]
    - name: Build with Maven
      run: mvn -B package --file pom.xml
